/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf --transform
Author: Hafizh_Mohamad (https://sketchfab.com/Alif.Hafizh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asus-gaming-5889a20ef39f491784b01c542dd23046
Title: Asus Gaming
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/asus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material__27} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material__30} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material__32} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['06___Default']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['06___Default']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['07___Default']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['08___Default']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Material__34} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.wire_000000000} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.wire_008061138} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.wire_022022022} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.wire_032032032} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.wire_115115115} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.wire_135006006} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.wire_135006006} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.wire_176026026} />
      </group>
    </group>
  )
}

useGLTF.preload('/asus-transformed.glb')
